src/Entity/Afschrijving.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="afschrijving")
 */
class Afschrijving {

  public function __construct() {
    $this->datum = new \DateTime();
  }

  /**
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   * @ORM\Column(type="integer")
   */
  private $id;
  /**
   * @ORM\ManyToOne(targetEntity="Artikel", inversedBy="afschrijvingartikel")
   * @ORM\JoinColumn(name="artikel_id", referencedColumnName="id")
   */
  private $artikel;
  /**
   * @ORM\Column(type="integer")
   */
  private $aantal;
  /**
   * @ORM\Column(type="string")
   */
  private $reden;
  /**
   * @ORM\Column(type="string", nullable=true)
   */
  private $reden_text = null;
  /**
   * @ORM\Column(type="datetime")
   */
  private $datum;
  /**
   * @ORM\Column(type="boolean")
   */
  private $shishapen = false;

  /**
   * @return mixed
   */
  public function getId() {
    return $this->id;
  }

  /**
   * @param mixed $id
   */
  public function setId($id) {
    $this->id = $id;
  }

  /**
   * @return mixed
   */
  public function getArtikel() {
    return $this->artikel;
  }

  /**
   * @param mixed $artikel
   */
  public function setArtikel(Artikel $artikel): void {
    $this->artikel = $artikel;
  }

  /**
   * @return mixed
   */
  public function getAantal() {
    return $this->aantal;
  }

  /**
   * @param mixed $aantal
   */
  public function setAantal($aantal) {
    $this->aantal = $aantal;
  }

  /**
   * @return mixed
   */
  public function getReden() {
    return $this->reden;
  }

  /**
   * @param mixed $reden
   */
  public function setReden($reden) {
    $this->reden = $reden;
  }

  /**
   * @return mixed
   */
  public function getRedenText() {
    return $this->reden_text;
  }

  /**
   * @param mixed $reden_text
   */
  public function setRedenText($reden_text) {
    $this->reden_text = $reden_text;
  }

  /**
   * @return mixed
   */
  public function getDatum() {
    return $this->datum;
  }

  /**
   * @param mixed $datum
   */
  public function setDatum($datum): void {
    $this->datum = $datum;
  }

  /**
   * @return mixed
   */
  public function getShishapen() {
    return $this->shishapen;
  }

  /**
   * @param mixed $shishapen
   */
  public function setShishapen($shishapen): void {
    $this->shishapen = $shishapen;
  }



}

src/Controller/VoorraadController.php
<?php

namespace App\Controller;

use App\Entity\Afschrijving;
use App\Entity\Artikel;
use App\Entity\Klantenbestelling;
use App\Entity\KlantenbestellingArtikel;
use App\Form\AfschrijfType;
use App\Form\ArtikelenVerkopenType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class VoorraadController extends Controller {

  public function __construct() {
    $this->array = null;
  }

  /**
   * @Route("/voorraad/voorraadartikel", name="voorraad_voorraadArtikelIndex")
   */
  public function voorraadArtikelIndex() {
    $em = $this->getDoctrine()->getManager();

    $artikelen = $artikelen0 = $artikelen1 = $artikelen2 = null;

    if ($this->get('session')->get('mode') == 'default') {
      $artikelen0 = $em->getRepository(Artikel::class)->findBy(['populariteit' => 0, 'shishapen' => false]);
      $artikelen1 = $em->getRepository(Artikel::class)->findBy(['populariteit' => 1, 'shishapen' => false]);
      $artikelen2 = $em->getRepository(Artikel::class)->findBy(['populariteit' => 2, 'shishapen' => false]);
    } else {
      $artikelen = $em->getRepository(Artikel::class)->findBy(['shishapen' => true]);
    }

    return $this->render('voorraad/voorraad_artikel.html.twig', [
        'artikelen' => $artikelen,
        'artikelen0' => $artikelen0,
        'artikelen1' => $artikelen1,
        'artikelen2' => $artikelen2,
    ]);
  }

  /**
   * @Route("/voorraad/artikelenverkopen", name="voorraad_artikelenVerkopenIndex")
   */
  public function artikelenVerkopenIndex(Request $request) {
    $em = $this->getDoctrine()->getManager();

    if ($this->get('session')->get('mode') == 'default') {
      $shishaOption = false;
    } else if ($this->get('session')->get('mode') == 'shisha') {
      $shishaOption = true;
    }

    //Klantenbestelling wordt aangemaakt
    $klantenbestelling = new Klantenbestelling();
    $form = $this->createForm(ArtikelenVerkopenType::class, $klantenbestelling, ['shishaOption' => $shishaOption]);

    $form->handleRequest($request);

    //Wanneer gebruiker het form opstuurt.
    if ($form->isSubmitted() && $form->isValid()) {

      $errorMessage = null;

      # Totalen variabelen
      $totaalGewicht = 0;
      $totaalPrijs = $form->get('verkoopprijs')->getData();


      for ($i = 1; $i <= 6; $i++) {
        $artikel = $form->get('artikel' . $i . '')->getData();

        if ($artikel) {
          if ($form->get('artikel' . $i . 'Aantal')->getData() !== null) {
            if ($artikel->canBeSold($form->get('artikel' . $i . 'Aantal')->getData())) {
              # Product van voorraad afhalen
              $artikel->setVoorraad($artikel->getVoorraad() - $form->get('artikel' . $i . 'Aantal')->getData());
              if ($form->get('verkocht')->getData() === true) {
                $artikel->setAfzet($artikel->getAfzet() + $form->get('artikel' . $i . 'Aantal')->getData());
              }
              $em->persist($artikel);

              # Product gewicht optellen bij totaalgewicht
              $totaalGewicht += ($artikel->getGewicht() * $form->get('artikel' . $i . 'Aantal')->getData());

              $klantenbestellingArtikel = new KlantenbestellingArtikel();
              $klantenbestellingArtikel->setKlantenbestelling($klantenbestelling);
              $klantenbestellingArtikel->setArtikel($artikel);
              $klantenbestellingArtikel->setAantal($form->get('artikel' . $i . 'Aantal')->getData());
              $em->persist($klantenbestellingArtikel);

            } else {
              $errorMessage = "Het artikel: " . $artikel->getNaam() . " heeft niet genoeg voorraad. (Huidige vooraad: " . $artikel->getVoorraad() . ")";
              break;
            }
          } else {
            $errorMessage = "Het aantal van artikel " . $i . " is niet ingevuld.";
            break;
          }
        }
      }

      # Enveloppegewicht ophalen
      $enveloppeGewicht = $form->get('typeEnv')->getData();

      if ($enveloppeGewicht !== 0) {
        #Enveloppegewicht bij totaalgewicht optellen
        $totaalGewicht += $form->get('typeEnv')->getData();

        # Postzegels berekenen
        if ($totaalGewicht >= 0 && $totaalGewicht <= 15) {
          $postzegelAantal = 1;
        } else if ($totaalGewicht >= 16 && $totaalGewicht <= 45) {
          $postzegelAantal = 2;
        } else if ($totaalGewicht >= 46 && $totaalGewicht <= 95) {
          $postzegelAantal = 3;
        } else if ($totaalGewicht >= 96) {
          $postzegelAantal = 4;
        }
        # Postzegels ophalen uit database en van voorraad afschrijven
        $postzegels = $em->getRepository(Artikel::class)->find(1);
        if ($postzegelAantal <= $postzegels->getVoorraad()) {
          $postzegels->setVoorraad($postzegels->getVoorraad() - $postzegelAantal);
          $em->persist($postzegels);
        } else {
          $errorMessage = "Je hebt niet genoeg postzegels op voorraad. (Huidige voorraad: " . $postzegels->getVoorraad() . ")";
        }
      } else {
        $postzegelAantal = 0;
      }
      $klantenbestelling->setPostzegels($postzegelAantal);

      # Berekenen van adres
      if ($form->get('postcode')->getData() != null) {
        $this->berekenAdres($form->get('postcode')->getData(), $form->get('huisnummer')->getData(), $form->get('toevoegsel')->getData());
        $klantenbestelling->setAdres($this->getStraat() . " " . $form->get('huisnummer')->getData() . $form->get('toevoegsel')->getData());
        $klantenbestelling->setStad($this->getStad());
      } else {
        $klantenbestelling->setPostcode("Niet ingevuld");
        $klantenbestelling->setAdres("Niet ingevuld");
        $klantenbestelling->setStad("Niet ingevuld");
      }

      # Zet totaalgewicht in klantenbestelling
      $klantenbestelling->setTotaalgewicht($totaalGewicht);

      # Maak van de klantenbestelling een shishapen klantenbestelling
      if ($this->get('session')->get('mode') == 'default') {
        $klantenbestelling->setShishapen(false);
      } else if ($this->get('session')->get('mode') == 'shisha') {
        $klantenbestelling->setShishapen(true);
      }

      # Zet totaalprijs in klantenbestelling
      $klantenbestelling->setVerkoopprijs($totaalPrijs);

      $em->persist($klantenbestelling);

      # Klantenbestelling aanmaken en redirect als er GEEN enkele error message is
      if (!$errorMessage) {
        $em->flush();

        $this->addFlash('success', "Klantenbestelling succesvol aangemaakt!");
        $orderID = $klantenbestelling->getId();
        return $this->redirectToRoute('klantenbestellingen_show', array('id' => $orderID));
      } else {
        $this->addFlash('danger', $errorMessage);
      }
    }

    return $this->render('voorraad/artikelen_verkopen.html.twig', [
        'form' => $form->createView(),
    ]);

  }

  /**
   * @Route("/voorraad/afschrijving", name="voorraad_afschrijvingIndex")
   */
  public function afschrijvingIndex(Request $request) {
    $em = $this->getDoctrine()->getManager();

    $afschrijving = new Afschrijving();

    if ($this->get('session')->get('mode') == 'default') {
      $shishaOption = false;
    } else if ($this->get('session')->get('mode') == 'shisha') {
      $shishaOption = true;
      $afschrijving->setShishapen(true);
    }

    $form = $this->createForm(AfschrijfType::class, $afschrijving, ['shishaOption' => $shishaOption]);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $errorMessage = null;

      $afschrijving->setArtikel($form->get('artikel')->getData());

      $artikel = $form->get('artikel')->getData();

      if ($artikel->getVoorraad() < $afschrijving->getAantal()) {
        $errorMessage = "Het artikel: " . $artikel->getNaam() . " heeft niet genoeg voorraad. (Huidige vooraad: " . $artikel->getVoorraad() . ")";
      }
      $artikel->setVoorraad($artikel->getVoorraad() - $afschrijving->getAantal());

      $em->persist($afschrijving);
      $em->persist($artikel);

      if (!$errorMessage) {
        $em->flush();
        $this->addFlash('success','Product succesvol afgeschreven!');
      } else {
        $this->addFlash('danger', $errorMessage);
      }

      return $this->redirectToRoute('voorraad_afschrijvingIndex');
    }

    $afschrijvingen = $em->getRepository(Afschrijving::class)->findAll();

    return $this->render('voorraad/afschrijving.html.twig', [
      'form' => $form->createView(),
      'afschrijvingen' => $afschrijvingen,
    ]);
  }

  /**
   * @Route("/voorraad/afschrijving/{id}", name="voorraad_afschrijvingShow")
   */
  public function afschrijvingShow($id) {
    $em = $this->getDoctrine()->getManager();

    $afschrijving = $em->getRepository(Afschrijving::class)->find($id);

    if (!$afschrijving) {
      throw $this->createNotFoundException('Afschrijving niet gevonden');
    }

    return $this->render('voorraad/afschrijvingshow.html.twig', [
        'afschrijving' => $afschrijving,
    ]);
  }


  public function berekenAdres($postcode, $huisnummer, $toevoegsel = null) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
// De headers worden altijd meegestuurd als array
    $headers = array();
    $headers[] = 'X-Api-Key: EeqQrrSEewAakfeR6dQ8YTUpN9p5eYakROGXSs90';

// De URL naar de API call
    $url = 'https://api.postcodeapi.nu/v2/addresses/?postcode=' . $postcode . '&number=' . $huisnummer . '&letter=' . $toevoegsel . '';

    $curl = curl_init($url);


    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

// Indien de server geen TLS ondersteunt kun je met
// onderstaande optie een onveilige verbinding forceren.
// Meestal is dit probleem te herkennen aan een lege response.
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

// De ruwe JSON response
    $response = curl_exec($curl);
// Gebruik json_decode() om de response naar een PHP array te converteren

templates/voorraad/afschrijving.html.twig
{% extends 'layout.html.twig' %}

{% block title %} Voorraad | Afschrijving {% endblock %}

{% block content %}

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Nieuwe afschrijving</h5>
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

        {{ form_row(form.artikel) }}
        {{ form_row(form.aantal) }}
        {{ form_row(form.reden) }}
        {{ form_row(form.redenText) }}

        <button type="submit" class="btn btn-primary btn-sm my-2"><i class="fas fa-minus"></i> Afschrijven</button>

        {# Token CSRF #}
        {{ form_widget(form._token) }}
        {{ form_end(form, {'render_rest': false}) }}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Vorige afschrijvingen</h5>
        <table class="table table-hover table-sm">
          <thead>
          <tr>
            {% if app.session.get('mode') == 'default' %}
            <th style="width: 20%;">Categorie</th>
            <th style="width: 30%">Naam</th>
            {% elseif app.session.get('mode') == 'shisha' %}
            <th style="width: 50%">Smaak</th>
            {% endif %}
            <th style="width: 10%">Aantal</th>
            <th style="width: 20%">Reden</th>
            <th style="width: 10%">Datum</th>
            <th style="width: 10%; min-width: 100px">Acties</th>
          </tr>
          </thead>
          <tbody>
          {% for afschrijving in afschrijvingen %}
            <tr>
              {% if app.session.get('mode') == 'default' %}
                <td>{{ afschrijving.artikel.categorie }}</td>
                <td>{{ afschrijving.artikel.naam }}</td>
              {% elseif app.session.get('mode') == 'shisha' %}
                <td>{{ afschrijving.artikel.naam }}</td>
              {% endif %}
              <td>{{ afschrijving.aantal }}</td>
              <td>{{ afschrijving.reden }}</td>
              <td>{{ afschrijving.datum|date('d-m-Y') }}</td>
              <td>
                <a class="btn btn-success btn-sm mx-1"
                   href="{{ path('voorraad_afschrijvingShow', {'id': afschrijving.id}) }}"><i
                          class="fas fa-eye"></i> Show</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>



{% endblock %}

templates/voorraad/afschrijvingshow.html.twig
{% extends 'layout.html.twig' %}

{% block title %} Voorraad | Afschrijving {% endblock %}

{% block content %}

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Afschrijving</h5>

        <table class="table table-borderless table-hover">
          <tr>
            <th>Afschrijving ID:</th>
            <td>{{ afschrijving.id }}</td>
          </tr>
          {% if app.session.get('mode') == 'default' %}
            <tr>
              <th>Artikel:</th>
              <td>{{ afschrijving.artikel.naam }}</td>
            </tr>
            <tr>
              <th>Categorie:</th>
              <td>{{ afschrijving.artikel.categorie }}</td>
            </tr>
          {% elseif app.session.get('mode') == 'shisha' %}
            <tr>
              <th>Smaak:</th>
              <td>{{ bestelling.artikel.naam }}</td>
            </tr>
          {% endif %}
          <tr>
            <th>Aantal:</th>
            <td>{{ afschrijving.aantal }}</td>
          </tr>
          <tr>
            <th>Reden:</th>
            <td>{{ afschrijving.reden }}</td>
          </tr>
          <tr>
            <th>Extra reden:</th>
            <td>{{ afschrijving.redenText }}</td>
          </tr>
          <tr>
            <th>Datum:</th>
            <td>{{ afschrijving.datum|date('d-m-Y H:i:s') }}</td>
          </tr>
        </table>

        <button type="button" class="btn btn-danger btn-sm" onclick="window.history.back()"><i class="fas fa-arrow-left"></i> Terug</button>

      </div>
    </div>
  </div>

{% endblock %}

templates/voorraad/artikelen_verkopen.html.twig
{% extends 'layout.html.twig' %}

{% block title %} Voorraad | Artikelen verkopen {% endblock %}

{% block content %}

  {#Laat eventuele errors zien op de pagina#}
  {% for msg in app.session.flashBag.get('error') %}
    <div class="alert alert-danger alert-dismissible fade show">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>ERROR!</strong> {{ msg }}
    </div>
  {% endfor %}

  {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Koper en verzend informatie:</h5>
        {{ form_row(form.koper) }}
        {% if is_granted('ROLE_USER') %}
          <div class="row">
            <div class="col-md-6 col-sm-12">
              {{ form_row(form.postcode) }}
            </div>
            <div class="col-md-3 col-sm-12">
              {{ form_row(form.huisnummer) }}
            </div>
            <div class="col-md-3 col-sm-12">
              {{ form_row(form.toevoegsel) }}
            </div>
          </div>
          {{ form_row(form.typeEnv) }}
          {{ form_row(form.marktplaatsaccount) }}
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Artikelen:</h5>
        <div class="row">
          <div class="col-lg-4 col-sm-10">
            {{ form_row(form.artikel1) }}
          </div>
          <div class="col-lg-2 col-sm-2">
            {{ form_row (form.artikel1Aantal) }}
          </div>
          <div class="col-lg-4 col-sm-10">
            {{ form_row(form.artikel2) }}
          </div>
          <div class="col-lg-2 col-sm-2">
            {{ form_row (form.artikel2Aantal) }}
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-sm-10">
            {{ form_row(form.artikel3) }}
          </div>
          <div class="col-lg-2 col-sm-2">
            {{ form_row (form.artikel3Aantal) }}
          </div>
          <div class="col-lg-4 col-sm-10">
            {{ form_row(form.artikel4) }}
          </div>
          <div class="col-lg-2 col-sm-2">
            {{ form_row (form.artikel4Aantal) }}
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-sm-10">
            {{ form_row(form.artikel5) }}
          </div>
          <div class="col-lg-2 col-sm-2">
            {{ form_row (form.artikel5Aantal) }}
          </div>
          <div class="col-lg-4 col-sm-10">
            {{ form_row(form.artikel6) }}
          </div>
          <div class="col-lg-2 col-sm-2">
            {{ form_row (form.artikel6Aantal) }}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Betalingsinformatie:</h5>
        {{ form_row(form.betaalmethode) }}
        {{ form_row(form.verkoopprijs) }}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <h5>Overige informatie:</h5>
        {{ form_row(form.verkocht) }}
        {{ form_row(form.extraInfo) }}
      </div>
    </div>
  </div>

  <button type="submit" class="btn btn-primary btn-sm my-2"><i class="fas fa-shopping-cart"></i> Verkopen</button>

  {# Token CSRF #}
  {{ form_widget(form._token) }}
  {{ form_end(form, {'render_rest': false}) }}

{% endblock %}

templates/voorraad/voorraad_artikel.html.twig
{% extends 'layout.html.twig' %}

{% block title %} Voorraad | Voorraad per artikel {% endblock %}

{% block content %}
  {#SHISHA MODE OFF#}
  {% if app.session.get('mode') == 'default' %}
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <h5>Artikelen:</h5>
          <a class="btn btn-dark btn-block my-2" onclick="this.blur();" data-toggle="collapse" href="#artikelen0"
             role="button" aria-expanded="false" aria-controls="artikelen0">
            <h5 class="">Specials</h5>
          </a>
          <div class="collapse show my-2" id="artikelen0">
            <table class="table table-hover table-sm table-responsive-md">
              <thead>
              <tr>
                <th style="width: 40%">Categorie</th>
                <th style="width: 30%">Naam</th>
                <th style="width: 15%">Huidige voorraad</th>
                <th style="width: 15%">Minimale voorraad</th>
              </tr>
              </thead>
              <tbody>
              {% for artikel in artikelen0 %}
                <tr>
                  <td>{{ artikel.categorie }}</td>
                  <td>{{ artikel.naam }}</td>
                  <td>
                    {{ artikel.voorraad }}
                    {% if artikel.voorraad == 0 %}
                      <span class="ml-2 badge badge-danger badge-pill">Voorraad op!</span>
                    {% elseif artikel.voorraad < artikel.minimaleVoorraad and artikel.voorraad != 0 %}
                      <span class="ml-2 badge badge-primary badge-pill">Onder MV!</span>
                    {% endif %}
                  </td>
                  <td>
                    {% if artikel.minimaleVoorraad == null %}
                      <span class="badge badge-danger">Niet ingevuld!</span>
                    {% else %}
                      {{ artikel.minimaleVoorraad }}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <a class="btn btn-dark btn-block my-2" onclick="this.blur();" data-toggle="collapse" href="#artikelen1"
             role="button" aria-expanded="false" aria-controls="artikelen1">
            <h5 class="">Actieve verkoop</h5>
          </a>
          <div class="collapse my-2" id="artikelen1">
            <table class="table table-hover table-sm ">
              <thead>
              <tr>
                <th style="width: 40%">Categorie</th>
                <th style="width: 30%">Naam</th>
                <th style="width: 15%">Huidige voorraad</th>
                <th style="width: 15%">Minimale voorraad</th>
              </tr>
              </thead>
              <tbody>
              {% for artikel in artikelen1 %}
                <tr>
                  <td>{{ artikel.categorie }}</td>
                  <td>{{ artikel.naam }}</td>
                  <td>
                    {{ artikel.voorraad }}
                    {% if artikel.voorraad == 0 %}
                      <span class="ml-2 badge badge-danger badge-pill">Voorraad op!</span>
                    {% elseif artikel.voorraad < artikel.minimaleVoorraad and artikel.voorraad != 0 %}
                      <span class="ml-2 badge badge-primary badge-pill">Onder MV!</span>
                    {% endif %}
                  </td>
                  <td>
                    {% if artikel.minimaleVoorraad == null %}
                      <span class="badge badge-danger">Niet ingevuld!</span>
                    {% else %}
                      {{ artikel.minimaleVoorraad }}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <a class="btn btn-dark btn-block my-2" onclick="this.blur();" data-toggle="collapse" href="#artikelen2"
             role="button" aria-expanded="false" aria-controls="artikelen2">
            <h5 class="">Blacklist</h5>
          </a>
          <div class="collapse my-2" id="artikelen2">
            <table class="table table-hover table-sm ">
              <thead>
              <tr>
                <th style="width: 40%">Categorie</th>
                <th style="width: 30%">Naam</th>
                <th style="width: 15%">Huidige voorraad</th>
                <th style="width: 15%">Minimale voorraad</th>
              </tr>
              </thead>
              <tbody>
              {% for artikel in artikelen2 %}
                <tr>
                  <td>{{ artikel.categorie }}</td>
                  <td>{{ artikel.naam }}</td>
                  <td>
                    {{ artikel.voorraad }}
                    {% if artikel.voorraad == 0 %}
                      <span class="ml-2 badge badge-danger badge-pill">Voorraad op!</span>
                    {% elseif artikel.voorraad < artikel.minimaleVoorraad and artikel.voorraad != 0 %}
                      <span class="ml-2 badge badge-primary badge-pill">Onder MV!</span>
                    {% endif %}
                  </td>
                  <td>
                    {% if artikel.minimaleVoorraad == null %}
                      <span class="badge badge-danger">Niet ingevuld!</span>
                    {% else %}
                      {{ artikel.minimaleVoorraad }}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    {#SHISHA MODE ON#}
  {% elseif app.session.get('mode') == 'shisha' %}
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <h5>Artikelen:</h5>
          <table class="table table-hover table-sm ">
            <thead>
            <tr>
              <th style="width: 70%">Naam</th>
              <th style="width: 15%">Huidige voorraad</th>
              <th style="width: 15%">Minimale voorraad</th>
            </tr>
            </thead>
            <tbody>
            {% for artikel in artikelen %}
              <tr>
                <td>{{ artikel.naam }}</td>
                <td>
                  {{ artikel.voorraad }}
                  {% if artikel.voorraad == 0 %}
                    <span class="ml-2 badge badge-danger badge-pill">Voorraad op!</span>
                  {% elseif artikel.voorraad < artikel.minimaleVoorraad and artikel.voorraad != 0 %}
                    <span class="ml-2 badge badge-primary badge-pill">Onder MV!</span>
                  {% endif %}
                </td>
                <td>
                  {% if artikel.minimaleVoorraad == null %}
                    <span class="badge badge-danger">Niet ingevuld!</span>
                  {% else %}
                    {{ artikel.minimaleVoorraad }}
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}